# Generated by Django 3.0.4 on 2020-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('quantity', models.PositiveIntegerField()),
                ('salt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Salt Information')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
            ],
        ),
    ]
