# Generated by Django 3.0.4 on 2020-03-28 09:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_create_announcement_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Body'),
        ),
    ]
