# Generated by Django 3.0.4 on 2020-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_make_date_field_optional'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(check=models.Q(('date_posted__isnull', False), ('is_posted__isnull', True)), name='active_post_must_have_date'),
        ),
    ]
