# Generated by Django 3.0.4 on 2020-03-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_add_is_available_field_to_doctor'),
        ('appointments', '0002_rename_field_and_add_is_cancelled_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
