version: "3"
services:
  db:
    image: "postgres:12-alpine"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env_files/postgres_env.env
  web:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.dev
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    depends_on:
      - db
    env_file:
      - ./env_files/django_env.env
      - ./env_files/postgres_env.env
    ports:
      - "8000:8000"
volumes:
  postgres_data:
