version: "3"

services:

  web:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.test
    env_file:
      - ./dev_env_files/django_env.env
      - ./dev_env_files/postgres_env.env
    entrypoint: dockerfiles/docker-entrypoint.test.sh
