# Generated by Django 3.0.4 on 2020-03-26 14:21

from django.db import migrations, models
import doctor.utils


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_create_doctor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='doctor_default.png', null=True, upload_to=doctor.utils.image_upload_util, validators=[doctor.utils.image_file_size_validator], verbose_name='Display Picture'),
        ),
    ]
