# Generated by Django 3.0.4 on 2020-03-26 14:35

from django.db import migrations, models
import doctor.utils


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_add_default_to_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor_default.png', upload_to=doctor.utils.image_upload_util, validators=[doctor.utils.image_file_size_validator], verbose_name='Display Picture'),
        ),
    ]
