# Generated by Django 3.0.4 on 2020-03-26 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_create_medicine_model'),
        ('student', '0003_add_meta_options_and_alter_quantity_field_visithistory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='medicines_given',
        ),
        migrations.RemoveField(
            model_name='visithistory',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MedicineGivenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.Medicine')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.VisitHistory')),
            ],
            options={
                'verbose_name_plural': 'Medicine given histories',
            },
        ),
    ]
